version: "3"
services:
  # For this PoC, we want to automatically
  # have Liferay secrets written into Vault.
  init:
    build:
      dockerfile: Dockerfile
      context: init
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-only-token
    depends_on:
      - vault
  # Vault with Liferay secrets
  # store under "secret/liferay".
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      # We use it in dev mode (insecure in production).
      VAULT_DEV_ROOT_TOKEN_ID: dev-only-token
  # Liferay DXP 7.4 (u42) with our own image based on the official one
  # where we installed Envconsul and updated the entrypoint accordingly.
  liferay:
    build:
      dockerfile: Dockerfile
      context: liferay
      args:
        - ENVCONSUL_VERSION=0.13.0
    ports:
      - "8080:8080"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-only-token
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://db/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
    volumes:
      - liferay_data:/opt/liferay/data
    depends_on:
      - db
      - vault
  # Database with MySQL 5.7.
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lportal
      MYSQL_USER: ray
      MYSQL_PASSWORD: super-secret-password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    depends_on:
      - vault
volumes:
  liferay_data:
  db_data:
